#!/usr/bin/env python3
"""Talia 3A Multi-word verbs: reguły 4 typów, znaczenia czasowników i tłumaczenia PL → EN.

Uruchom z katalogu repo: python decks/multi_word_verbs_3a.py
Nadpisuje pliki TSV w output/. Nie zmieniaj pierwszych pól istniejących wierszy –
od nich zależy GUID notatki w Anki (zmiana = nowa karta i utrata historii powtórek).
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "scripts"))
from cardlib import (examples_block, grammar_explanation, meaning_fields,  # noqa: E402
                     mistakes_block, translation_fields, type_tags, write_tsv)

BASE_TAGS = "multi-word-verbs unit-3a"


def grammar_row(rule, formula, usage, keyverbs, tip, examples, mistakes, tags):
    return [rule, grammar_explanation(formula, usage, tip, signal=keyverbs), examples_block(examples),
            mistakes_block(mistakes), f"fce grammar {BASE_TAGS} {tags}".strip()]


def pv_row(verb, meanings, note, examples, synonyms, base, types):
    return [verb, meaning_fields(meanings, note), examples_block(examples), synonyms,
            f"fce phrasal-verbs {base} {BASE_TAGS} {type_tags(types)}"]


def tr_row(pl, hint, answer, alt, expl, wrong, types):
    return [*translation_fields(pl, hint, answer, alt, expl, wrong), "translation",
            f"fce use-of-english translation {BASE_TAGS} {type_tags(types)}"]


# ---------------------------------------------------------------- GRAMMAR
GRAMMAR = [
    grammar_row(
        "Multi-word verbs – what are they?",
        "<code>verb + particle</code> → sit down, try sth out<br><code>verb + particle + particle</code> → come up with sth",
        [
            "Czasownik + jedna lub dwie partykuły (up, down, off, out, away, into, on, with…) tworzą <b>jedno znaczenie</b>.",
            "Czasem znaczenie jest dosłowne i łatwe do odgadnięcia: <b>sit down</b> = usiąść, <b>fall down</b> = upaść.",
            "Częściej jest idiomatyczne i trzeba go uczyć się jak nowego słowa: <b>let sb down</b> = zawieść kogoś, <b>make sth up</b> = zmyślić.",
            "Inna nazwa: <b>phrasal verbs</b>.",
        ],
        "",
        "Phrasal verbs są wprost sprawdzane w Reading and Use of English Part 1 (multiple-choice cloze). W Part 4 (key word transformation) parafraza może wymagać zamiany zwykłego czasownika na multi-word verb, np. investigate → <b>look into</b>, disappoint → <b>let down</b>, test → <b>try out</b>.",
        [
            ("We <b>came up with</b> a new plan and decided to <b>try it out</b> at the weekend.",
             "Wymyśliliśmy nowy plan i postanowiliśmy wypróbować go w weekend."),
            ("Please <b>sit down</b> – the lesson is about to start.",
             "Proszę usiąść – lekcja zaraz się zacznie."),
            ("I promised to help, so I don't want to <b>let</b> my friends <b>down</b>.",
             "Obiecałem pomóc, więc nie chcę zawieść przyjaciół."),
        ],
        [
            ("Our team came up a great idea.", "Our team came up with a great idea.",
             "Partykuły są częścią czasownika – nie można żadnej pominąć. <b>come up</b> i <b>come up with</b> to różne czasowniki."),
            ("We ran out from milk.", "We ran out of milk.",
             "Partykuły są stałe – nie zamieniaj ich na inne przyimki, które pasują „po polsku” (z → from)."),
        ],
        "basics",
    ),
    grammar_row(
        "Transitive vs intransitive multi-word verbs",
        "<b>Intransitive</b> (bez dopełnienia): <code>subject + verb + particle</code> → The plane took off.<br>"
        "<b>Transitive</b> (z dopełnieniem): <code>subject + verb + particle + object</code> → She looks after her brother.",
        [
            "<b>Transitive</b> (przechodnie) potrzebują dopełnienia (sth/sb): throw sth away, look after sb.",
            "<b>Intransitive</b> (nieprzechodnie) nie mają dopełnienia: go away, fall down.",
            "Nieprzechodniego czasownika nie można „użyć na kimś”: <b>NOT</b> <i>go somebody away</i> → <i>tell somebody to go away</i>.",
        ],
        "",
        "Polskie „się” (obudzić się, uspokoić się, poddać się) często podpowiada wersję <b>bez dopełnienia</b>: wake up, calm down, give up.",
        [
            ("<b>Go away</b>! I'm trying to work.", "Idź sobie! Próbuję pracować."),
            ("Could you <b>look after</b> my dog this weekend?", "Czy możesz zaopiekować się moim psem w ten weekend?"),
            ("The old man slipped and <b>fell down</b>.", "Starszy mężczyzna poślizgnął się i upadł."),
        ],
        [
            ("The teacher went the noisy students away.", "The teacher told the noisy students to go away.",
             "<b>go away</b> jest nieprzechodni – nie może mieć dopełnienia (tu: the students)."),
            ("Don't worry about the problem – I'll look into.", "Don't worry about the problem – I'll look into it.",
             "<b>look into</b> jest przechodni – zawsze potrzebuje dopełnienia (tu: it)."),
        ],
        "transitivity",
    ),
    grammar_row(
        "Type 1 – intransitive: verb + particle",
        "<code>subject + verb + particle</code> (+ okolicznik czasu / miejsca)<br>My alarm went off at six.",
        [
            "<b>Brak dopełnienia</b> – po partykule nie ma sth/sb.",
            "Po partykule może stać okolicznik: stay up <b>late</b>, go away <b>for the weekend</b>.",
            "Czasowników nieprzechodnich nie używamy w stronie biernej.",
        ],
        "wake up, go away, fall down, stay up, break up, sit down, take off, calm down (+ z notatek: go off, fall apart)",
        "Type 1 często odpowiada polskiemu czasownikowi z „się”: obudzić się, uspokoić się, rozpadać się. Nie tłumacz tego „się” jako <i>myself</i>.",
        [
            ("I usually <b>wake up</b> at six, but yesterday my alarm didn't <b>go off</b>.",
             "Zwykle budzę się o szóstej, ale wczoraj nie zadzwonił mi budzik."),
            ("We <b>stayed up</b> until 2 a.m. watching the match.",
             "Siedzieliśmy do drugiej w nocy, oglądając mecz."),
            ("The plane <b>took off</b> on time despite the fog.",
             "Samolot wystartował o czasie mimo mgły."),
        ],
        [
            ("I woke up myself at seven.", "I woke up at seven.",
             "Polskiego „się” nie tłumaczymy jako <i>myself</i> – <b>wake up</b> już znaczy „obudzić się”."),
            ("The alarm was gone off at six.", "The alarm went off at six.",
             "Czasowniki nieprzechodnie (Type 1) nie mają strony biernej."),
        ],
        "type-1",
    ),
    grammar_row(
        "Type 2 – transitive, separable: verb + object + particle",
        "<code>verb + noun/pronoun + particle</code> → throw the box away / throw it away<br>"
        "<b>OR</b> <code>verb + particle + noun</code> → throw away the box",
        [
            "Dopełnienie może stać <b>między</b> czasownikiem a partykułą albo <b>po</b> partykule.",
            "Pozycję wybieramy w zależności od tego, czym jest dopełnienie: zaimek / krótka fraza / długa fraza (osobne karty).",
            "Bez dopełnienia ten sam czasownik bywa Type 1 o innym znaczeniu: take off (wystartować) vs take sth off (zdjąć).",
        ],
        "wake sb up, take sth off, calm sb down, try sth out, figure sth out, make sth up, throw sth away, pick sth up, let sb down (+ z notatek: put sth up, put sb up)",
        "W słowniku Type 2 rozpoznasz po zapisie <b>sth/sb między czasownikiem a partykułą</b>: throw sth away, let sb down.",
        [
            ("Can you <b>pick up</b> that pen? / Can you <b>pick</b> that pen <b>up</b>?",
             "Możesz podnieść ten długopis?"),
            ("I <b>took off</b> my shoes. / I <b>took</b> my shoes <b>off</b>.",
             "Zdjąłem buty."),
            ("Don't <b>let</b> your team <b>down</b>.",
             "Nie zawiedź swojej drużyny."),
        ],
        [
            ("I'll wake up you at seven.", "I'll wake you up at seven.",
             "Zaimek (you) w Type 2 stoi między czasownikiem a partykułą."),
            ("It was hot, so he took off.", "It was hot, so he took his jacket off.",
             "Bez dopełnienia <b>take off</b> znaczy „wystartować” (Type 1). Żeby powiedzieć „zdjąć”, musisz dodać co."),
        ],
        "type-2",
    ),
    grammar_row(
        "Type 2 – word order with pronouns",
        "<code>verb + PRONOUN + particle</code><br>✅ throw <b>them</b> away &nbsp; ❌ throw away them",
        [
            "Zaimek (it, them, me, you, him, her, us) stoi <b>prawie zawsze między</b> czasownikiem a partykułą.",
            "To najczęściej testowany punkt szyku multi-word verbs.",
        ],
        "",
        "Zapamiętaj rytm: <i>pick it up, throw it away, try it out, figure it out, put me up, let me down</i>.",
        [
            ("Your old notes are useless now – just <b>throw them away</b>.",
             "Twoje stare notatki są już bezużyteczne – po prostu je wyrzuć."),
            ("I can't <b>figure it out</b> – can you help me?",
             "Nie mogę tego rozgryźć – pomożesz mi?"),
            ("My flight is at 6 a.m. Can you <b>wake me up</b> at four?",
             "Mój lot jest o szóstej rano. Obudzisz mnie o czwartej?"),
        ],
        [
            ("Please throw away them!", "Please throw them away!",
             "Zaimek nie może stać po partykule w Type 2."),
            ("That's not true – you made up it!", "That's not true – you made it up!",
             "Tak samo z <b>it</b>: make it up, nie make up it."),
        ],
        "type-2 word-order",
    ),
    grammar_row(
        "Type 2 – word order with short and long noun phrases",
        "<b>Krótka fraza</b> (do ok. 3 słów): <code>throw those old shoes away</code> = <code>throw away those old shoes</code><br>"
        "<b>Długa fraza</b>: <code>verb + particle + LONG noun phrase</code> → throw away the shoes that are falling apart",
        [
            "Krótka fraza rzeczownikowa (the box, my old shoes) – obie pozycje są poprawne.",
            "Długa fraza (np. ze zdaniem względnym who / that / which) – stawiamy ją <b>po partykule</b>.",
            "Powód: słuchacz nie powinien długo czekać na partykułę, która nadaje czasownikowi znaczenie.",
        ],
        "",
        "W writingu przy długim dopełnieniu bezpieczniej postawić partykułę od razu po czasowniku.",
        [
            ("Please <b>throw away</b> all the magazines that are lying under the bed.",
             "Proszę, wyrzuć wszystkie czasopisma, które leżą pod łóżkiem."),
            ("She <b>tried</b> the new camera <b>out</b>. / She <b>tried out</b> the new camera.",
             "Wypróbowała nowy aparat."),
            ("We need to <b>pick up</b> the students who are waiting at the station.",
             "Musimy odebrać uczniów, którzy czekają na dworcu."),
        ],
        [
            ("Please throw the magazines that are lying under the bed away.",
             "Please throw away the magazines that are lying under the bed.",
             "Długa fraza z <i>that…</i> powinna stać po partykule."),
            ("He made the story about his grandfather's adventures in Africa up.",
             "He made up the story about his grandfather's adventures in Africa.",
             "Przy długim dopełnieniu partykuła „ginie” na końcu zdania – przenieś ją za czasownik."),
        ],
        "type-2 word-order",
    ),
    grammar_row(
        "Type 3 – transitive, inseparable: verb + particle + object",
        "<code>verb + particle + noun/pronoun</code><br>✅ look after <b>him</b> &nbsp; ❌ look him after",
        [
            "Dopełnienie stoi <b>zawsze po partykule</b> – także zaimek.",
            "Nic nie wchodzi między czasownik a partykułę (partykuła działa tu jak przyimek).",
            "<b>be into sth</b>: odmieniamy <b>be</b> – I'm into, she's into, they were into.",
        ],
        "look into sth, focus on sth, believe in sth, live for sth, be into sth, look after sb",
        "W słowniku zapis <b>look after sb</b>, <b>look into sth</b> – sth/sb na końcu oznacza, że czasownika nie rozdzielamy.",
        [
            ("Calm down! I'll <b>look into it</b>.", "Spokojnie! Zajmę się tym."),
            ("My grandma <b>looked after me</b> when my parents were at work.",
             "Babcia opiekowała się mną, kiedy rodzice byli w pracy."),
            ("I'm really <b>into</b> photography at the moment.",
             "Ostatnio bardzo wciągnęła mnie fotografia."),
        ],
        [
            ("Who will look the children after?", "Who will look after the children?",
             "Type 3 jest nierozdzielny – dopełnienie zawsze po partykule."),
            ("The police will look it into.", "The police will look into it.",
             "Nawet zaimek (it) stoi po partykule – inaczej niż w Type 2."),
        ],
        "type-3",
    ),
    grammar_row(
        "Type 4 – two particles: verb + particle + particle + object",
        "<code>verb + particle 1 + particle 2 + noun/pronoun</code><br>✅ run out of <b>it</b> &nbsp; ❌ run it out of",
        [
            "Zawsze ma dopełnienie – stoi ono <b>na końcu</b>, po obu partykułach.",
            "Nie rozdzielamy: nic nie wchodzi między czasownik a partykuły.",
            "Jeśli po Type 4 stoi czasownik, ma formę <b>-ing</b>: get away with cheating.",
        ],
        "come up with sth, look down on sb, look up to sb, run out of sth, fall out with sb, go on about sth, get away with sth",
        "Type 4 często zastępuje jeden czasownik: admire → <b>look up to</b>, think of → <b>come up with</b>, argue → <b>fall out with</b>.",
        [
            ("How did we <b>run out of</b> bananas again?", "Jak to możliwe, że znowu skończyły nam się banany?"),
            ("I've always <b>looked up to</b> my older brother.", "Zawsze podziwiałem starszego brata."),
            ("He cheated in the test and <b>got away with it</b>.", "Ściągał na teście i uszło mu to na sucho."),
        ],
        [
            ("We've run out milk.", "We've run out of milk.",
             "W Type 4 nie można pominąć drugiej partykuły."),
            ("He always gets away with to cheat.", "He always gets away with cheating.",
             "Po partykule (with) czasownik ma formę -ing."),
        ],
        "type-4",
    ),
    grammar_row(
        "Verbs that are both transitive and intransitive",
        "<b>Type 1:</b> <code>subject + verb + particle</code> → The plane took off.<br>"
        "<b>Type 2:</b> <code>subject + verb + object + particle</code> → I took my shoes off.",
        [
            "Wiele multi-word verbs ma obie wersje: wake up / wake sb up, calm down / calm sb down, give up / give sth up, take off / take sth off.",
            "Znaczenie może zostać podobne (obudzić się / obudzić kogoś) albo zmienić się całkowicie (wystartować / zdjąć).",
            "W razie wątpliwości sprawdź w słowniku, czy dana wersja ma dopełnienie.",
        ],
        "wake up, give up, take off, calm down",
        "Zdanie-klucz: <i>When you <b>wake up</b>, try not to <b>wake the dog up</b>!</i>",
        [
            ("I <b>woke up</b> at five because the neighbours' dog <b>woke me up</b>.",
             "Obudziłem się o piątej, bo obudził mnie pies sąsiadów."),
            ("After the plane <b>took off</b>, I <b>took</b> my shoes <b>off</b>.",
             "Po starcie samolotu zdjąłem buty."),
            ("She was panicking, so I tried to <b>calm her down</b>. Finally she <b>calmed down</b>.",
             "Panikowała, więc próbowałem ją uspokoić. W końcu się uspokoiła."),
        ],
        [
            ("The baby woke up me.", "The baby woke me up.",
             "Wersja z dopełnieniem to Type 2 – zaimek stoi w środku."),
            ("She gave up to smoke.", "She gave up smoking.",
             "Po <b>give up</b> czasownik ma formę -ing."),
        ],
        "type-1 type-2",
    ),
    grammar_row(
        "Reading dictionary entries: sth / sb show the type",
        "go away → <b>Type 1</b> (brak sth/sb)<br>throw <b>sth</b> away → <b>Type 2</b> (sth w środku)<br>"
        "look after <b>sb</b> → <b>Type 3</b> (sb na końcu, jedna partykuła)<br>look up to <b>sb</b> → <b>Type 4</b> (dwie partykuły + sb)",
        [
            "Brak sth/sb = czasownik nieprzechodni (Type 1).",
            "sth/sb między czasownikiem a partykułą = rozdzielny (Type 2).",
            "sth/sb na końcu po jednej partykule = nierozdzielny (Type 3).",
            "Dwie partykuły + sth/sb = Type 4.",
        ],
        "",
        "Zapisuj nowe multi-word verbs <b>zawsze z sth/sb we właściwym miejscu</b> (let sb down, a nie samo let down) – od razu zapamiętasz typ.",
        [
            ("<b>Go away</b> and leave me alone!", "Idź sobie i zostaw mnie w spokoju!"),
            ("I trusted you and you <b>let me down</b>.", "Zaufałem ci, a ty mnie zawiodłeś."),
            ("Who <b>looks after</b> your cat when you travel?", "Kto opiekuje się twoim kotem, kiedy podróżujesz?"),
            ("Never <b>look down on</b> people who earn less than you.", "Nigdy nie patrz z góry na ludzi, którzy zarabiają mniej niż ty."),
        ],
        [
            ("You let down me. (bo w notatkach: „let down = zawieść”)", "You let me down. (zapis: let sb down)",
             "Zapis z <b>sb</b> w środku od razu pokazuje, gdzie wstawić zaimek."),
            ("I'll look him after. (bo w notatkach: „look after = opiekować się”)", "I'll look after him. (zapis: look after sb)",
             "Zapis z <b>sb</b> na końcu pokazuje, że czasownika nie rozdzielamy."),
        ],
        "dictionary-skills",
    ),
    grammar_row(
        "One verb, two types: sth runs out vs sb runs out of sth",
        "<b>Type 1:</b> <code>thing + run out</code> → The milk has run out.<br>"
        "<b>Type 4:</b> <code>person + run out of + thing</code> → We've run out of milk.",
        [
            "Druga partykuła „otwiera” miejsce na dopełnienie: run out → run out <b>of</b> sth, break up → break up <b>with</b> sb, fall out → fall out <b>with</b> sb.",
            "Zwróć uwagę na podmiot: <i>The milk ran out</i> (mleko się skończyło) vs <i>We ran out of milk</i> (skończyło nam się mleko).",
        ],
        "run out (of), break up (with), fall out (with), get away (with)",
        "Typowa transformacja w Part 4: <i>There's no milk left.</i> → <i>We have <b>run out of</b> milk.</i>",
        [
            ("Time <b>ran out</b> before I finished the last task.", "Czas się skończył, zanim dokończyłem ostatnie zadanie."),
            ("We <b>ran out of</b> time before the last task.", "Zabrakło nam czasu na ostatnie zadanie."),
            ("Tom and Lisa <b>broke up</b> last month. / Lisa <b>broke up with</b> Tom last month.",
             "Tom i Lisa rozstali się w zeszłym miesiącu. / Lisa zerwała z Tomem w zeszłym miesiącu."),
        ],
        [
            ("The milk has run out of.", "The milk has run out. / We have run out of milk.",
             "Gdy podmiotem jest rzecz, która się kończy – Type 1 bez <i>of</i>."),
            ("She broke up him.", "She broke up with him.",
             "Z osobą potrzebujesz drugiej partykuły: break up <b>with</b> sb (Type 4)."),
        ],
        "type-1 type-4",
    ),
]

# ---------------------------------------------------------------- PHRASAL VERBS
PV = [
    # ---- Type 1
    pv_row("wake up / wake (sb) up",
           [("obudzić się", "to stop sleeping"),
            ("obudzić kogoś", "to make someone stop sleeping")],
           "<b>Type 1</b> (obudzić się) i <b>Type 2</b> (obudzić kogoś): wake the kids up / wake up the kids / wake them up (NIE wake up them).",
           [("I usually <b>wake up</b> at 6:30 on weekdays.", "W dni robocze zwykle budzę się o 6:30."),
            ("Can you <b>wake me up</b> at seven tomorrow?", "Obudzisz mnie jutro o siódmej?"),
            ("Be quiet or you'll <b>wake the baby up</b>!", "Bądź cicho, bo obudzisz dziecko!")],
           "awake, awaken, rouse", "wake", ["1", "2"]),
    pv_row("go away",
           [("odejść, iść sobie; wyjechać (np. na urlop)", "to leave a place or a person; to leave home for a holiday"),
            ("(o bólu, problemie) minąć, zniknąć", "(of a pain or problem) to disappear")],
           "<b>Type 1</b> – nieprzechodni, bez dopełnienia. NIE: <i>go somebody away</i> → <i>tell somebody to go away</i>.",
           [("<b>Go away</b>! I'm trying to study.", "Idź sobie! Próbuję się uczyć."),
            ("We're <b>going away</b> for the weekend.", "Wyjeżdżamy na weekend."),
            ("I took a painkiller, but the headache didn't <b>go away</b>.", "Wziąłem tabletkę przeciwbólową, ale ból głowy nie minął."),
            ("The problem won't just <b>go away</b> if you ignore it.", "Problem nie zniknie sam, jeśli będziesz go ignorować.")],
           "leave, depart, disappear", "go", ["1"]),
    pv_row("fall down",
           [("upaść, przewrócić się; (o budynku) zawalić się", "to fall to the ground; (of a building) to collapse")],
           "<b>Type 1</b> – nieprzechodni. Uwaga: <i>fall down the stairs</i> = spaść ze schodów (tu <i>the stairs</i> to miejsce, a nie dopełnienie).",
           [("She slipped on the ice and <b>fell down</b>.", "Poślizgnęła się na lodzie i upadła."),
            ("That old building looks as if it's going to <b>fall down</b>.", "Ten stary budynek wygląda, jakby miał się zaraz zawalić.")],
           "fall, collapse, tumble", "fall", ["1"]),
    pv_row("stay up",
           [("nie kłaść się spać, siedzieć do późna", "to go to bed later than usual")],
           "<b>Type 1</b> – nieprzechodni. Typowe połączenia: stay up late, stay up all night, stay up until midnight.",
           [("I <b>stayed up</b> late to finish my essay.", "Siedziałem do późna, żeby skończyć wypracowanie."),
            ("The kids are allowed to <b>stay up</b> until ten at weekends.", "W weekendy dzieci mogą nie kłaść się spać do dziesiątej.")],
           "stay awake, keep awake", "stay", ["1"]),
    pv_row("break up",
           [("rozstać się, zerwać (o parze)", "to end a romantic relationship"),
            ("(o połączeniu, sygnale) przerywać, rwać się", "(of a phone signal) to become unclear, so the speaker can't be heard properly")],
           "<b>Type 1</b> – nieprzechodni: They broke up. Z osobą → <b>Type 4</b>: <i>break up with sb</i> (She broke up with him).",
           [("After five years together, they <b>broke up</b> last summer.", "Po pięciu latach razem rozstali się zeszłego lata."),
            ("Why did you <b>break up with</b> your girlfriend?", "Dlaczego zerwałeś z dziewczyną?"),
            ("Sorry, you're <b>breaking up</b> – I can't hear you.", "Przepraszam, przerywa ci – nie słyszę cię."),
            ("Your signal is <b>breaking up</b>, so I'll call you back.", "Rwie ci się połączenie, więc oddzwonię.")],
           "split up, separate; (signal) cut out", "break", ["1", "4"]),
    pv_row("sit down",
           [("usiąść, siadać", "to move into a sitting position")],
           "<b>Type 1</b> – nieprzechodni, znaczenie dosłowne (sit + down). Bez dopełnienia: Please sit down.",
           [("Please <b>sit down</b> and make yourself comfortable.", "Proszę usiąść i się rozgościć."),
            ("We <b>sat down</b> at the table and started talking about the plan.", "Usiedliśmy przy stole i zaczęliśmy rozmawiać o planie.")],
           "sit, take a seat, be seated", "sit", ["1"]),
    pv_row("take off",
           [("(o samolocie) wystartować", "(of a plane) to leave the ground and start flying"),
            ("(o karierze, produkcie) nagle odnieść sukces, nabrać rozpędu", "to suddenly become successful or popular")],
           "<b>Type 1</b> – nieprzechodni. Z dopełnieniem to inny czasownik: <i>take sth off</i> = zdjąć (Type 2).",
           [("Our plane <b>took off</b> an hour late because of the storm.", "Nasz samolot wystartował z godzinnym opóźnieniem z powodu burzy."),
            ("Please fasten your seatbelts – we're about to <b>take off</b>.", "Proszę zapiąć pasy – za chwilę startujemy."),
            ("Her career really <b>took off</b> after her first film.", "Jej kariera naprawdę nabrała rozpędu po pierwszym filmie."),
            ("The app <b>took off</b> among teenagers almost overnight.", "Aplikacja niemal z dnia na dzień zrobiła furorę wśród nastolatków.")],
           "depart, lift off; (success) boom, flourish", "take", ["1"]),
    pv_row("calm down / calm (sb) down",
           [("uspokoić się", "to become less angry, upset or excited"),
            ("uspokoić kogoś", "to make someone less angry, upset or excited")],
           "<b>Type 1</b> (uspokoić się) i <b>Type 2</b> (uspokoić kogoś): Calm down! / I tried to calm her down (NIE calm down her).",
           [("<b>Calm down</b>! Shouting won't help.", "Uspokój się! Krzyk nic nie pomoże."),
            ("It took me an hour to <b>calm down</b> after the argument.", "Po kłótni uspokajałem się przez godzinę."),
            ("The teacher managed to <b>calm the children down</b>.", "Nauczycielce udało się uspokoić dzieci."),
            ("She was so nervous that nothing could <b>calm her down</b>.", "Była tak zdenerwowana, że nic nie mogło jej uspokoić.")],
           "relax, settle down; soothe, reassure", "calm", ["1", "2"]),
    pv_row("go off",
           [("(o budziku, alarmie) zadzwonić, włączyć się; (o bombie) wybuchnąć", "(of an alarm) to start ringing; (of a bomb) to explode"),
            ("(o jedzeniu) zepsuć się", "(of food) to become bad and not safe to eat")],
           "<b>Type 1</b> – nieprzechodni. Podmiotem jest urządzenie / rzecz: My alarm went off (NIE: <i>I went off my alarm</i>).",
           [("My alarm <b>went off</b> at six, but I didn't hear it.", "Budzik zadzwonił o szóstej, ale go nie usłyszałem."),
            ("The fire alarm <b>went off</b> in the middle of the exam.", "W środku egzaminu włączył się alarm przeciwpożarowy."),
            ("Don't drink that milk – it's <b>gone off</b>.", "Nie pij tego mleka – zepsuło się."),
            ("The fish will <b>go off</b> if you don't put it in the fridge.", "Ryba się zepsuje, jeśli nie włożysz jej do lodówki.")],
           "ring, sound, explode; (food) go bad, spoil", "go", ["1"]),
    pv_row("fall apart",
           [("rozpadać się (o starym lub tandetnym przedmiocie)", "to break into pieces because it is old or badly made"),
            ("(o planie, związku, człowieku) posypać się, załamać się", "(of a plan, relationship or person) to stop working or be unable to cope")],
           "<b>Type 1</b> – nieprzechodni. W materiale: <i>those old shoes that are nearly falling apart</i>.",
           [("My trainers are so old that they're <b>falling apart</b>.", "Moje buty sportowe są tak stare, że się rozpadają."),
            ("This cheap furniture started to <b>fall apart</b> after a month.", "Te tanie meble zaczęły się rozpadać po miesiącu."),
            ("Our holiday plans <b>fell apart</b> when the airline cancelled our flight.", "Nasze plany wakacyjne legły w gruzach, kiedy linia lotnicza odwołała nasz lot."),
            ("He almost <b>fell apart</b> after he lost his job.", "Prawie się załamał po utracie pracy.")],
           "disintegrate, collapse, break down", "fall", ["1"]),
    pv_row("give up / give (sth) up",
           [("poddać się, zrezygnować", "to stop trying"),
            ("rzucić coś, przestać coś robić (nałóg, hobby)", "to stop doing or having something")],
           "<b>Type 1</b> (Don't give up!) i <b>Type 2</b> (give up sugar / give it up – NIE give up it). Po give up czasownik z <b>-ing</b>: give up smoking.",
           [("The exam is hard, but don't <b>give up</b>!", "Egzamin jest trudny, ale się nie poddawaj!"),
            ("I tried to solve the puzzle for an hour and then <b>gave up</b>.", "Przez godzinę próbowałem rozwiązać łamigłówkę, a potem się poddałem."),
            ("My dad <b>gave up</b> smoking ten years ago.", "Mój tata rzucił palenie dziesięć lat temu."),
            ("I loved playing the guitar, but I had to <b>give it up</b> when I started working.", "Uwielbiałem grać na gitarze, ale musiałem z tego zrezygnować, kiedy zacząłem pracować.")],
           "quit, abandon, surrender", "give", ["1", "2"]),
    # ---- Type 2
    pv_row("take (sth) off",
           [("zdjąć (ubranie, buty, biżuterię)", "to remove a piece of clothing, shoes or jewellery"),
            ("wziąć wolne (od pracy)", "to have a period of time away from work: take a day / a week off")],
           "<b>Type 2</b> – rozdzielny: take off your shoes / take your shoes off / take them off (NIE take off them). Bez dopełnienia = wystartować (Type 1).",
           [("Please <b>take off</b> your shoes before you come in.", "Proszę zdjąć buty przed wejściem."),
            ("It was hot, so I <b>took my jacket off</b>.", "Było gorąco, więc zdjąłem kurtkę."),
            ("These boots are wet – <b>take them off</b>!", "Te buty są mokre – zdejmij je!"),
            ("I'm going to <b>take a few days off</b> after the exam.", "Po egzaminie wezmę kilka dni wolnego.")],
           "remove; (from work) have time off", "take", ["2"]),
    pv_row("try (sth) out",
           [("wypróbować, przetestować", "to use something to find out if it works or if you like it")],
           "<b>Type 2</b> – rozdzielny: try out the app / try the app out / try it out (NIE try out it).",
           [("We came up with some new ideas and decided to <b>try them out</b>.", "Wpadliśmy na kilka nowych pomysłów i postanowiliśmy je wypróbować."),
            ("You can <b>try out</b> the software for free for 30 days.", "Możesz przez 30 dni za darmo testować to oprogramowanie.")],
           "test, trial, sample", "try", ["2"]),
    pv_row("figure (sth / sb) out",
           [("rozgryźć, zrozumieć, wykombinować (jak coś zrobić)", "to understand something or find the answer by thinking about it"),
            ("rozgryźć kogoś (zrozumieć jego zachowanie)", "to understand why someone behaves as they do")],
           "<b>Type 2</b> – rozdzielny: figure out the answer / figure the answer out / figure it out (NIE figure out it). Często z pytaniem: figure out how / why / what…",
           [("I can't <b>figure out</b> how to use this new printer.", "Nie mogę rozgryźć, jak obsługiwać tę nową drukarkę."),
            ("It took me ages to <b>figure it out</b>, but I finally solved the problem.", "Długo mi zajęło, zanim to rozgryzłem, ale w końcu rozwiązałem problem."),
            ("My new boss is strange – I can't <b>figure him out</b>.", "Mój nowy szef jest dziwny – nie mogę go rozgryźć."),
            ("She's so quiet that nobody can <b>figure her out</b>.", "Jest tak cicha, że nikt nie potrafi jej rozgryźć.")],
           "work out, understand, solve", "figure", ["2"]),
    pv_row("make (sth) up",
           [("zmyślić, wymyślić (historię, wymówkę)", "to invent a story, an excuse, etc., often to trick someone")],
           "<b>Type 2</b> – rozdzielny: make up an excuse / make an excuse up / make it up (NIE make up it). Uwaga: <i>make up (with sb)</i> = pogodzić się – inne znaczenie.",
           [("He <b>made up</b> an excuse about his car breaking down.", "Zmyślił wymówkę, że zepsuł mu się samochód."),
            ("That's not true – you're <b>making it up</b>!", "To nieprawda – zmyślasz!"),
            ("My little sister loves <b>making up</b> stories about dragons.", "Moja młodsza siostra uwielbia wymyślać historie o smokach.")],
           "invent, fabricate, concoct", "make", ["2"]),
    pv_row("throw (sth) away",
           [("wyrzucić (do śmieci), pozbyć się", "to get rid of something you don't want or need any more"),
            ("zmarnować (szansę, wysiłek)", "to waste a chance or an advantage")],
           "<b>Type 2</b> – rozdzielny: throw away the shoes / throw the shoes away / throw them away (NIE throw away them). Długa fraza → po partykule.",
           [("Don't <b>throw away</b> those boxes – we can use them when we move.", "Nie wyrzucaj tych pudeł – przydadzą się przy przeprowadzce."),
            ("These jeans have a hole in them, so I'm going to <b>throw them away</b>.", "Te dżinsy mają dziurę, więc je wyrzucę."),
            ("He <b>threw away</b> the chance to play for the national team.", "Zmarnował szansę gry w reprezentacji."),
            ("You've studied so hard – don't <b>throw it all away</b> now.", "Tak ciężko się uczyłeś – nie zmarnuj tego teraz.")],
           "discard, dispose of, get rid of; (chance) waste", "throw", ["2"]),
    pv_row("pick (sth / sb) up",
           [("podnieść (z podłogi, ze stołu)", "to lift something or someone from a surface"),
            ("odebrać kogoś / coś (np. z dworca, z poczty)", "to collect someone or something from a place"),
            ("nauczyć się mimochodem (języka, nawyku)", "to learn a skill or a language without studying it formally")],
           "<b>Type 2</b> – rozdzielny: pick up the kids / pick the kids up / pick them up (NIE pick up them).",
           [("The baby dropped her toy, so I <b>picked it up</b>.", "Dziecko upuściło zabawkę, więc ją podniosłem."),
            ("I'll <b>pick you up</b> from the station at eight.", "Odbiorę cię z dworca o ósmej."),
            ("Can you <b>pick up</b> my parcel from the post office?", "Możesz odebrać moją paczkę z poczty?"),
            ("She <b>picked up</b> Spanish while she was working in Madrid.", "Nauczyła się hiszpańskiego, kiedy pracowała w Madrycie.")],
           "lift; collect, fetch; acquire", "pick", ["2"]),
    pv_row("let (sb) down",
           [("zawieść kogoś, rozczarować", "to disappoint someone by not doing what they expected or needed")],
           "<b>Type 2</b> – rozdzielny; osoba zwykle stoi w środku: let me down, let your team down (NIE let down me).",
           [("I promised I'd help, and I don't want to <b>let you down</b>.", "Obiecałem, że pomogę, i nie chcę cię zawieść."),
            ("Our best player <b>let the team down</b> in the final.", "Nasz najlepszy zawodnik zawiódł drużynę w finale."),
            ("Many voters feel <b>let down</b> by the government.", "Wielu wyborców czuje się zawiedzionych przez rząd.")],
           "disappoint, fail", "let", ["2"]),
    pv_row("put (sth) up",
           [("powiesić, wywiesić (plakat, obraz, ogłoszenie)", "to fix something to a wall so that people can see it"),
            ("rozstawić, postawić (namiot, płot)", "to build or raise something, e.g. a tent or a fence"),
            ("podnieść (cenę, czynsz)", "to increase a price")],
           "<b>Type 2</b> – rozdzielny: put up a poster / put a poster up / put it up (NIE put up it). Uwaga: <i>put sb up</i> = przenocować kogoś (osobna karta).",
           [("I <b>put up</b> a poster of my favourite band in my room.", "Powiesiłem w pokoju plakat mojego ulubionego zespołu."),
            ("It took us twenty minutes to <b>put the tent up</b>.", "Rozstawienie namiotu zajęło nam dwadzieścia minut."),
            ("Our landlord is <b>putting up</b> the rent again.", "Nasz właściciel znowu podnosi czynsz.")],
           "hang, display, erect; (price) raise", "put", ["2"]),
    pv_row("put (sb) up",
           [("przenocować kogoś, przyjąć kogoś na noc", "to let someone stay in your home for a short time")],
           "<b>Type 2</b> – rozdzielny; z osobą w środku: Can you put me up? (NIE put up me). Nie myl z <i>put up with sb/sth</i> = znosić kogoś/coś (Type 4).",
           [("Can you <b>put me up</b> for a couple of nights?", "Czy możesz mnie przenocować przez kilka nocy?"),
            ("My cousin <b>put us up</b> when we visited London.", "Kuzyn przenocował nas, kiedy byliśmy w Londynie.")],
           "accommodate, house, host", "put", ["2"]),
    # ---- Type 3
    pv_row("look into (sth)",
           [("zbadać, przyjrzeć się (sprawie), sprawdzić", "to examine the facts about a problem or a situation")],
           "<b>Type 3</b> – nierozdzielny: look into the problem / look into it (NIE look it into).",
           [("Thanks for your complaint – we'll <b>look into it</b> immediately.", "Dziękujemy za reklamację – natychmiast się temu przyjrzymy."),
            ("The police are <b>looking into</b> the cause of the accident.", "Policja bada przyczynę wypadku.")],
           "investigate, examine, explore", "look", ["3"]),
    pv_row("focus on (sth)",
           [("skupić się na, skoncentrować się na", "to give most of your attention to something")],
           "<b>Type 3</b> – nierozdzielny: focus on your goals / focus on it. Wariant: <i>focus your attention on sth</i>.",
           [("Turn off your phone and <b>focus on</b> your homework.", "Wyłącz telefon i skup się na zadaniu domowym."),
            ("In the exam, <b>focus on</b> what the question is actually asking.", "Na egzaminie skup się na tym, o co naprawdę chodzi w pytaniu.")],
           "concentrate on, centre on, pay attention to", "focus", ["3"]),
    pv_row("believe in (sth / sb)",
           [("wierzyć w istnienie czegoś", "to be sure that something exists"),
            ("wierzyć w kogoś / w słuszność czegoś", "to trust that someone will succeed or that an idea is right")],
           "<b>Type 3</b> – nierozdzielny: believe in ghosts / believe in yourself. Porównaj: <i>believe sb</i> = wierzyć komuś (że mówi prawdę).",
           [("Do you <b>believe in</b> ghosts?", "Wierzysz w duchy?"),
            ("My parents have always <b>believed in</b> me.", "Rodzice zawsze we mnie wierzyli."),
            ("I <b>believe in</b> giving everyone a second chance.", "Uważam, że każdemu należy się druga szansa.")],
           "trust, have faith in, support", "believe", ["3"]),
    pv_row("live for (sth)",
           [("żyć czymś / dla czegoś (uważać za najważniejsze w życiu)", "to consider something the most important thing in your life")],
           "<b>Type 3</b> – nierozdzielny: live for music / live for the weekend / live for it.",
           [("My brother <b>lives for</b> football – he watches every match.", "Mój brat żyje piłką nożną – ogląda każdy mecz."),
            ("Most of my colleagues just <b>live for</b> the weekend.", "Większość moich współpracowników żyje tylko weekendem.")],
           "be devoted to, be dedicated to, adore", "live", ["3"]),
    pv_row("be into (sth)",
           [("interesować się czymś, lubić coś, „wkręcić się” w coś", "to be very interested in an activity or a subject (informal)")],
           "<b>Type 3</b> – nierozdzielny; odmieniamy <b>be</b>: I'm into, she's into. Po <i>into</i>: rzeczownik albo <b>-ing</b> (I'm into cooking).",
           [("I'm really <b>into</b> photography at the moment.", "Ostatnio bardzo wciągnęła mnie fotografia."),
            ("She's not <b>into</b> watching sport on TV.", "Nie przepada za oglądaniem sportu w telewizji.")],
           "be keen on, be interested in, enjoy", "be", ["3"]),
    pv_row("look after (sb / sth)",
           [("opiekować się, dbać o", "to take care of someone or something")],
           "<b>Type 3</b> – nierozdzielny: look after the kids / look after them (NIE look them after).",
           [("Who <b>looks after</b> your dog when you're on holiday?", "Kto opiekuje się twoim psem, kiedy jesteś na wakacjach?"),
            ("You should <b>look after</b> yourself better and get more sleep.", "Powinieneś bardziej o siebie dbać i więcej spać.")],
           "take care of, care for, mind", "look", ["3"]),
    # ---- Type 4
    pv_row("come up with (sth)",
           [("wymyślić, wpaść na (pomysł, rozwiązanie)", "to think of an idea, a plan or a solution")],
           "<b>Type 4</b> – dwie partykuły, dopełnienie na końcu: come up with an idea / come up with it.",
           [("Who <b>came up with</b> the idea of a class trip to Kraków?", "Kto wpadł na pomysł wycieczki klasowej do Krakowa?"),
            ("We need to <b>come up with</b> a solution before Friday.", "Musimy wymyślić rozwiązanie przed piątkiem.")],
           "think of, devise, invent", "come", ["4"]),
    pv_row("look down on (sb)",
           [("patrzeć na kogoś z góry, lekceważyć kogoś", "to think that you are better than someone")],
           "<b>Type 4</b>: look down on people / look down on them. Przeciwieństwo: <i>look up to sb</i>.",
           [("He <b>looks down on</b> anyone who didn't go to university.", "Patrzy z góry na każdego, kto nie poszedł na studia."),
            ("You shouldn't <b>look down on</b> people because of their accent.", "Nie powinno się patrzeć na ludzi z góry z powodu ich akcentu.")],
           "despise, disdain, scorn", "look", ["4"]),
    pv_row("look up to (sb)",
           [("podziwiać kogoś, wzorować się na kimś", "to admire and respect someone")],
           "<b>Type 4</b>: look up to your parents / look up to her. Nie myl z <i>look sth up</i> (Type 2) = sprawdzić w słowniku.",
           [("I've always <b>looked up to</b> my grandfather.", "Zawsze podziwiałem dziadka."),
            ("Young players often <b>look up to</b> famous athletes.", "Młodzi zawodnicy często wzorują się na znanych sportowcach.")],
           "admire, respect, idolise", "look", ["4"]),
    pv_row("run out of (sth)",
           [("skończyć się (komuś), zabraknąć (komuś czegoś)", "to use all of something, so that there is none left")],
           "<b>Type 4</b>: We've run out of milk / run out of it. Gdy podmiotem jest rzecz → <b>Type 1</b> bez <i>of</i>: The milk has run out.",
           [("We've <b>run out of</b> coffee – can you buy some?", "Skończyła nam się kawa – możesz kupić?"),
            ("I <b>ran out of</b> time and couldn't finish the last question.", "Zabrakło mi czasu i nie dokończyłem ostatniego pytania."),
            ("Our money <b>ran out</b> after two weeks.", "Pieniądze skończyły nam się po dwóch tygodniach.")],
           "use up, exhaust, have none left", "run", ["4", "1"]),
    pv_row("fall out with (sb)",
           [("pokłócić się z kimś (i przestać się przyjaźnić)", "to argue with someone and stop being friendly with them")],
           "<b>Type 4</b>: fall out with a friend / fall out with him. Bez osoby → Type 1: <i>We fell out</i>. Powód kłótni: <i>fall out over sth</i>.",
           [("I <b>fell out with</b> my best friend over something really stupid.", "Pokłóciłem się z najlepszym przyjacielem o coś naprawdę głupiego."),
            ("She's <b>fallen out with</b> her neighbours again.", "Znowu pokłóciła się z sąsiadami.")],
           "argue, quarrel, clash", "fall", ["4"]),
    pv_row("go on about (sth)",
           [("ciągle o czymś gadać, nudzić o czymś", "to talk about something for a long time in a boring or annoying way")],
           "<b>Type 4</b>: go on about his car / go on about it. Często z <i>always</i> + Continuous: He's always going on about… Porównaj: <i>go on</i> = kontynuować (Type 1).",
           [("He's always <b>going on about</b> how much money he earns.", "Ciągle gada o tym, ile zarabia."),
            ("Please stop <b>going on about</b> the exam – you'll be fine!", "Przestań w kółko gadać o egzaminie – będzie dobrze!")],
           "ramble, harp on, drone on", "go", ["4"]),
    pv_row("get away with (sth)",
           [("ujść na sucho, uniknąć kary za coś", "to do something wrong without being punished or criticised")],
           "<b>Type 4</b>: get away with cheating / get away with it. Po <i>with</i>: rzeczownik albo <b>-ing</b>. Bez <i>with</i> → Type 1: <i>get away</i> = uciec, wyrwać się.",
           [("He copied his friend's homework and <b>got away with it</b>.", "Odpisał pracę domową od kolegi i uszło mu to na sucho."),
            ("You won't <b>get away with</b> lying to me!", "Okłamywanie mnie nie ujdzie ci na sucho!")],
           "escape punishment, go unpunished, evade", "get", ["4"]),
    # ---- z notatek (idiomy)
    pv_row("get your head around (sth)",
           [("ogarnąć, pojąć (coś trudnego lub zaskakującego)", "to manage to understand something difficult or surprising (informal)")],
           "<b>Idiom</b> (poza tabelą 4 typów): get + my / your / his… + head + around (round) + sth. Najczęściej w przeczeniu: <i>I can't get my head around it.</i>",
           [("I can't <b>get my head around</b> these new tax rules.", "Nie mogę ogarnąć tych nowych przepisów podatkowych."),
            ("It took me a while to <b>get my head around</b> the idea of moving abroad.", "Trochę mi zajęło, zanim oswoiłem się z myślą o przeprowadzce za granicę.")],
           "grasp, comprehend, make sense of", "get", ["idiom"]),
    pv_row("be hard up",
           [("być spłukanym, klepać biedę", "to have very little money (informal)")],
           "To <b>nie jest</b> multi-word verb, tylko wyrażenie przymiotnikowe: <b>be + hard up</b> (odmieniamy <i>be</i>: he's hard up, we were hard up). Nie ma dopełnienia.",
           [("He's a bit <b>hard up</b> at the moment, so he can't come on the trip.", "Jest teraz trochę spłukany, więc nie może jechać na wycieczkę."),
            ("When I was a student, I was always <b>hard up</b>.", "Kiedy byłem studentem, zawsze byłem bez grosza.")],
           "broke, skint, short of money", "be", ["idiom"]),
]

# ---------------------------------------------------------------- TRANSLATION (Use of English)
T1 = "Type 1 – bez dopełnienia."
T2 = "Type 2 – rozdzielny."
T3 = "Type 3 – nierozdzielny."
T4 = "Type 4 – dwie partykuły."

TR = [
    # ---- Type 1
    tr_row("Zwykle budzę się o szóstej, ale dziś nie zadzwonił mi budzik.", "wake up · go off",
           "I usually wake up at six, but today my alarm didn't go off.", "",
           (T1, "Oba czasowniki są nieprzechodnie. „Budzę się” to po prostu <b>wake up</b>, a podmiotem <b>go off</b> jest budzik."),
           "I usually wake up myself at six…", ["1"]),
    tr_row("Idź sobie! Próbuję się skupić.", "go away",
           "Go away! I'm trying to concentrate.", "",
           (T1, "<b>go away</b> nie ma dopełnienia – nie można „odesłać kogoś” tym czasownikiem (NIE go somebody away)."),
           "", ["1"]),
    tr_row("Ból głowy nie minął, więc poszedłem do lekarza.", "go away",
           "My headache didn't go away, so I went to the doctor.", "The headache didn't go away, so I went to see a doctor.",
           (T1, "<b>go away</b> w znaczeniu „minąć, zniknąć” – podmiotem jest ból."),
           "", ["1"]),
    tr_row("Mój dziadek poślizgnął się na lodzie i upadł.", "fall down",
           "My grandfather slipped on the ice and fell down.", "",
           (T1, "<b>fall down</b> – nieprzechodni, bez dopełnienia i bez „się”."),
           "", ["1"]),
    tr_row("Wczoraj siedziałem do trzeciej w nocy, żeby skończyć projekt.", "stay up",
           "Yesterday I stayed up until 3 a.m. to finish the project.", "I stayed up until three in the morning yesterday to finish the project.",
           (T1, "Po <b>stay up</b> stoi okolicznik czasu (until 3 a.m.), a nie dopełnienie."),
           "", ["1"]),
    tr_row("Rozstali się po trzech latach.", "break up",
           "They broke up after three years.", "They broke up after three years together.",
           (T1, "Dwie osoby jako podmiot → <b>break up</b> bez dopełnienia. Z jedną osobą: <i>She broke up with him</i> (Type 4)."),
           "", ["1"]),
    tr_row("Przepraszam, przerywa ci – oddzwonię za chwilę.", "break up",
           "Sorry, you're breaking up – I'll call you back in a minute.", "",
           (T1, "<b>break up</b> o słabym sygnale; podmiotem jest rozmówca (<i>you're breaking up</i>). Uwaga: <i>call you back</i> to Type 2 z zaimkiem w środku."),
           "", ["1"]),
    tr_row("Proszę, usiądź – musimy porozmawiać.", "sit down",
           "Please sit down – we need to talk.", "Sit down, please – we need to talk.",
           (T1, "<b>sit down</b> – bez dopełnienia i bez <i>yourself</i>."),
           "", ["1"]),
    tr_row("Samolot wystartował z dwugodzinnym opóźnieniem.", "take off",
           "The plane took off two hours late.", "The plane took off with a two-hour delay.",
           (T1, "<b>take off</b> bez dopełnienia = wystartować."),
           "", ["1"]),
    tr_row("Uspokój się! Wszystko będzie dobrze.", "calm down",
           "Calm down! Everything will be fine.", "Calm down! Everything's going to be OK.",
           (T1, "„Uspokój się” = <b>calm down</b> – polskiego „się” nie tłumaczymy jako <i>yourself</i>."),
           "", ["1"]),
    tr_row("Nie poddawaj się – jesteś już blisko!", "give up",
           "Don't give up – you're almost there!", "Don't give up – you're so close!",
           (T1, "<b>give up</b> bez dopełnienia = poddać się."),
           "", ["1"]),
    tr_row("Mleko się zepsuło – nie pij go.", "go off",
           "The milk has gone off – don't drink it.", "",
           (T1, "<b>go off</b> o jedzeniu = zepsuć się. Present Perfect, bo skutek jest widoczny teraz."),
           "The milk has gone off itself.", ["1"]),
    tr_row("Nasze plany legły w gruzach, kiedy odwołano lot.", "fall apart",
           "Our plans fell apart when the flight was cancelled.", "Our plans fell apart when our flight was cancelled.",
           (T1, "<b>fall apart</b> – nieprzechodni; o planach, związkach, ludziach = posypać się, załamać się."),
           "", ["1"]),
    tr_row("Czas się skończył, zanim dokończyłem pisać.", "run out",
           "Time ran out before I finished writing.", "",
           (T1, "Podmiotem jest rzecz, która się kończy (time) → <b>run out</b> bez <i>of</i>. Porównaj: <i>I ran out of time</i> (Type 4)."),
           "Time ran out of before I finished writing.", ["1"]),
    # ---- Type 2
    tr_row("Obudź mnie o siódmej, proszę.", "wake up",
           "Please wake me up at seven.", "Wake me up at seven, please.",
           (T2, "Dopełnienie to zaimek (<b>me</b>) → stoi między czasownikiem a partykułą."),
           "Please wake up me at seven.", ["2"]),
    tr_row("Bądź cicho, bo obudzisz dziecko!", "wake up",
           "Be quiet or you'll wake the baby up!", "Be quiet or you'll wake up the baby!",
           (T2, "Krótka fraza (<b>the baby</b>) może stać w środku albo po partykule."),
           "", ["2"]),
    tr_row("Kiedy się obudzisz, postaraj się nie obudzić psa!", "wake up",
           "When you wake up, try not to wake the dog up!", "When you wake up, try not to wake up the dog!",
           ("Type 1 + Type 2.", "Ten sam czasownik: bez dopełnienia (obudzić się) i z dopełnieniem (obudzić psa)."),
           "", ["1", "2"]),
    tr_row("Zdejmij buty, zanim wejdziesz do salonu.", "take off",
           "Take your shoes off before you go into the living room.", "Take off your shoes before you go into the living room.",
           (T2, "<b>take sth off</b> = zdjąć. Krótka fraza (your shoes) – obie pozycje poprawne."),
           "", ["2"]),
    tr_row("Te buty są mokre – zdejmij je!", "take off",
           "These shoes are wet – take them off!", "",
           (T2, "Zaimek (<b>them</b>) zawsze w środku."),
           "These shoes are wet – take off them!", ["2"]),
    tr_row("Kiedy samolot wystartował, zdjąłem buty i zasnąłem.", "take off (×2)",
           "When the plane took off, I took my shoes off and fell asleep.", "When the plane took off, I took off my shoes and fell asleep.",
           ("Type 1 + Type 2.", "<b>take off</b> bez dopełnienia = wystartować; <b>take sth off</b> = zdjąć."),
           "", ["1", "2"]),
    tr_row("Uspokój się i pomóż mi uspokoić dzieci.", "calm down (×2)",
           "Calm down and help me calm the children down.", "Calm down and help me calm down the children.",
           ("Type 1 + Type 2.", "„Uspokoić się” = <b>calm down</b>; „uspokoić kogoś” = <b>calm sb down</b>."),
           "", ["1", "2"]),
    tr_row("Była tak zdenerwowana, że nie mogłem jej uspokoić.", "calm down",
           "She was so upset that I couldn't calm her down.", "She was so nervous that I couldn't calm her down.",
           (T2, "Zaimek (<b>her</b>) w środku."),
           "…I couldn't calm down her.", ["2"]),
    tr_row("Kupiłem nową aplikację i chcę ją dziś wypróbować.", "try out",
           "I've bought a new app and I want to try it out today.", "I bought a new app and I want to try it out today.",
           (T2, "Zaimek (<b>it</b>) w środku."),
           "…I want to try out it today.", ["2"]),
    tr_row("Wpadliśmy na kilka dobrych pomysłów i postanowiliśmy je wypróbować.", "come up with · try out",
           "We came up with some good ideas and decided to try them out.", "",
           ("Type 4 + Type 2.", "<b>come up with</b> – dopełnienie po obu partykułach; <b>try sth out</b> – zaimek w środku."),
           "…and decided to try out them.", ["2", "4"]),
    tr_row("Nie mogę tego rozgryźć!", "figure out",
           "I can't figure it out!", "",
           (T2, "„Tego” = <b>it</b> → zaimek w środku."),
           "I can't figure out it!", ["2"]),
    tr_row("Musimy wymyślić, jak dojechać na lotnisko.", "figure out",
           "We need to figure out how to get to the airport.", "We have to figure out how to get to the airport.",
           (T2, "Dopełnieniem jest całe pytanie (<b>how to get…</b>) – długa fraza, więc stoi po partykule."),
           "We need to figure how to get to the airport out.", ["2"]),
    tr_row("Nie wierzę ci – zmyśliłeś to!", "make up",
           "I don't believe you – you made it up!", "I don't believe you – you've made it up!",
           (T2, "Zaimek (<b>it</b>) w środku."),
           "…you made up it!", ["2"]),
    tr_row("Zmyślił wymówkę, żeby nie przyjść na spotkanie.", "make up",
           "He made up an excuse so that he didn't have to come to the meeting.", "He made an excuse up so he didn't have to go to the meeting.",
           (T2, "Krótka fraza (<b>an excuse</b>) – obie pozycje poprawne; częściej po partykule."),
           "", ["2"]),
    tr_row("Te gazety są stare – wyrzuć je.", "throw away",
           "These newspapers are old – throw them away.", "",
           (T2, "Zaimek (<b>them</b>) w środku."),
           "These newspapers are old – throw away them.", ["2"]),
    tr_row("Wyrzuć stare buty, które od lat leżą w szafie!", "throw away",
           "Throw away the old shoes that have been lying in the wardrobe for years!", "",
           (T2, "Długa fraza ze zdaniem względnym (<b>the old shoes that…</b>) → po partykule."),
           "Throw the old shoes that have been lying in the wardrobe for years away!", ["2"]),
    tr_row("Czy możesz podnieść tę kartkę z podłogi?", "pick up",
           "Can you pick up that piece of paper from the floor?", "Could you pick that piece of paper up off the floor?",
           (T2, "Fraza rzeczownikowa jest krótka – obie pozycje są poprawne; przy dłuższej frazie naturalniej postawić ją po partykule."),
           "", ["2"]),
    tr_row("Odbiorę cię z dworca o ósmej.", "pick up",
           "I'll pick you up from the station at eight.", "I'll pick you up at the station at eight.",
           (T2, "<b>pick sb up</b> = odebrać kogoś. Zaimek (<b>you</b>) w środku."),
           "I'll pick up you from the station at eight.", ["2"]),
    tr_row("Nauczyła się włoskiego, kiedy mieszkała w Rzymie.", "pick up",
           "She picked up Italian while she was living in Rome.", "She picked up Italian when she lived in Rome.",
           (T2, "<b>pick up</b> = nauczyć się mimochodem. Z nazwą języka zwykle po partykule."),
           "", ["2"]),
    tr_row("Obiecałeś, że przyjdziesz. Nie zawiedź mnie!", "let down",
           "You promised you'd come. Don't let me down!", "You promised to come. Don't let me down!",
           (T2, "Zaimek (<b>me</b>) w środku."),
           "Don't let down me!", ["2"]),
    tr_row("Nie chcę zawieść rodziców.", "let down",
           "I don't want to let my parents down.", "I don't want to let down my parents.",
           (T2, "Krótka fraza (<b>my parents</b>) – obie pozycje poprawne; z osobą częściej w środku."),
           "", ["2"]),
    tr_row("Powiesiłem nad biurkiem nowy plakat.", "put up",
           "I put up a new poster above my desk.", "I put a new poster up above my desk.",
           (T2, "<b>put sth up</b> = powiesić. Krótka fraza (a new poster) – obie pozycje poprawne."),
           "", ["2"]),
    tr_row("Możesz mnie przenocować w sobotę?", "put up",
           "Can you put me up on Saturday?", "Could you put me up on Saturday night?",
           (T2, "<b>put sb up</b> = przenocować kogoś. Zaimek (<b>me</b>) w środku."),
           "Can you put up me on Saturday?", ["2"]),
    tr_row("Ciocia nas przenocowała, kiedy byliśmy w Gdańsku.", "put up",
           "My aunt put us up when we were in Gdańsk.", "",
           (T2, "Zaimek (<b>us</b>) w środku."),
           "My aunt put up us when we were in Gdańsk.", ["2"]),
    tr_row("Miesiąc temu rzuciłem cukier.", "give up",
           "I gave up sugar a month ago.", "I gave sugar up a month ago.",
           (T2, "<b>give sth up</b> = rzucić coś. Krótka fraza – obie pozycje poprawne."),
           "", ["2"]),
    tr_row("Uwielbiał grać w tenisa, ale po kontuzji musiał z tego zrezygnować.", "give up",
           "He loved playing tennis, but he had to give it up after his injury.", "He loved playing tennis, but after his injury he had to give it up.",
           (T2, "„Z tego” = <b>it</b> → zaimek w środku."),
           "…he had to give up it after his injury.", ["2"]),
    # ---- Type 3
    tr_row("Spokojnie! Zajmę się tym.", "look into",
           "Calm down! I'll look into it.", "Don't worry! I'll look into it.",
           (T3, "W Type 3 zaimek (<b>it</b>) stoi <b>po</b> partykule – odwrotnie niż w Type 2."),
           "Calm down! I'll look it into.", ["3"]),
    tr_row("Policja bada przyczynę pożaru.", "look into",
           "The police are looking into the cause of the fire.", "",
           (T3, "Dopełnienie po partykule. Uwaga: <i>the police</i> łączy się z liczbą mnogą (are)."),
           "The police are looking the cause of the fire into.", ["3"]),
    tr_row("Skup się na pytaniu, a nie na zegarze.", "focus on",
           "Focus on the question, not on the clock.", "Focus on the question, not the clock.",
           (T3, "Dopełnienie zawsze po <b>on</b>."),
           "", ["3"]),
    tr_row("To ważne – musimy się na tym skupić.", "focus on",
           "It's important – we need to focus on it.", "This is important – we have to focus on it.",
           (T3, "Zaimek (<b>it</b>) po partykule: focus on it."),
           "…we need to focus it on.", ["3"]),
    tr_row("Wierzysz w duchy?", "believe in",
           "Do you believe in ghosts?", "",
           (T3, "<b>believe in sth</b> = wierzyć w istnienie czegoś."),
           "Do you believe ghosts?", ["3"]),
    tr_row("Nikt we mnie nie wierzył, ale mi się udało.", "believe in",
           "Nobody believed in me, but I did it.", "No one believed in me, but I succeeded.",
           (T3, "Zaimek (<b>me</b>) po partykule. <i>believe me</i> znaczyłoby „wierzyć mi (że mówię prawdę)”."),
           "Nobody believed me in, but I did it.", ["3"]),
    tr_row("Mój brat żyje muzyką.", "live for",
           "My brother lives for music.", "",
           (T3, "Dopełnienie po <b>for</b>; Present Simple, 3. osoba: <i>lives</i>."),
           "", ["3"]),
    tr_row("Ostatnio bardzo wciągnęło mnie gotowanie.", "be into",
           "I'm really into cooking at the moment.", "I've been really into cooking lately.",
           (T3, "<b>be into + -ing</b>. Odmieniamy <i>be</i>; podmiotem jest osoba, nie hobby."),
           "Cooking is really into me.", ["3"]),
    tr_row("Kto opiekuje się twoimi dziećmi, kiedy jesteś w pracy?", "look after",
           "Who looks after your children when you're at work?", "Who looks after your kids while you're at work?",
           (T3, "Dopełnienie po partykule."),
           "Who looks your children after when you're at work?", ["3"]),
    tr_row("Babcia jest chora, więc się nią opiekuję.", "look after",
           "My grandma is ill, so I'm looking after her.", "My grandmother is sick, so I'm looking after her.",
           (T3, "Zaimek (<b>her</b>) po partykule – odwrotnie niż w Type 2."),
           "…so I'm looking her after.", ["3"]),
    # ---- Type 4
    tr_row("Kto wpadł na ten pomysł?", "come up with",
           "Who came up with this idea?", "Who came up with that idea?",
           (T4, "Dopełnienie po obu partykułach."),
           "Who came up this idea with?", ["4"]),
    tr_row("Musimy wymyślić lepsze rozwiązanie.", "come up with",
           "We need to come up with a better solution.", "We have to come up with a better solution.",
           (T4, "Nie pomijaj <b>with</b>."),
           "We need to come up a better solution.", ["4"]),
    tr_row("On patrzy z góry na ludzi, którzy nie mówią po angielsku.", "look down on",
           "He looks down on people who don't speak English.", "",
           (T4, "Długie czy krótkie – dopełnienie w Type 4 zawsze na końcu."),
           "", ["4"]),
    tr_row("Zawsze podziwiałem swoją starszą siostrę.", "look up to",
           "I've always looked up to my older sister.", "I always looked up to my older sister.",
           (T4, "Present Perfect z <i>always</i> – podziw trwa do dziś."),
           "I've always looked my older sister up to.", ["4"]),
    tr_row("Znowu skończyły nam się banany!", "run out of",
           "We've run out of bananas again!", "",
           (T4, "Podmiotem jest osoba (we) → <b>run out of</b> + rzecz. Present Perfect – skutek widoczny teraz."),
           "We've run out bananas again!", ["4"]),
    tr_row("Zabrakło mi czasu na ostatnie zadanie.", "run out of",
           "I ran out of time for the last task.", "I ran out of time before the last task.",
           (T4, "„Zabrakło mi” → podmiotem jest <b>I</b>: I ran out of time."),
           "I ran out time for the last task.", ["4"]),
    tr_row("Pokłóciłem się z najlepszym przyjacielem o pieniądze.", "fall out with",
           "I fell out with my best friend over money.", "I fell out with my best friend about money.",
           (T4, "<b>fall out with sb over/about sth</b>."),
           "I fell out my best friend with over money.", ["4"]),
    tr_row("Zerwała z nim przez SMS-a.", "break up with",
           "She broke up with him by text.", "She broke up with him over text.",
           (T4, "Z osobą potrzebujesz drugiej partykuły: <b>break up with sb</b>."),
           "She broke up him by text.", ["4"]),
    tr_row("On ciągle gada o swoim nowym samochodzie.", "go on about",
           "He keeps going on about his new car.", "He's always going on about his new car.",
           (T4, "<b>keep + -ing</b> albo <b>always + Continuous</b> podkreśla, że to irytujące."),
           "He keeps going on his new car about.", ["4"]),
    tr_row("Ściągał na egzaminie i uszło mu to na sucho.", "get away with",
           "He cheated in the exam and got away with it.", "He cheated in the exam and got away with it completely.",
           (T4, "Zaimek (<b>it</b>) na końcu, po obu partykułach."),
           "…and got away it with.", ["4"]),
    tr_row("Okłamywanie nauczyciela nie ujdzie ci na sucho!", "get away with",
           "You won't get away with lying to the teacher!", "",
           (T4, "Po <b>with</b> czasownik z <b>-ing</b>: get away with lying."),
           "You won't get away with lie to the teacher!", ["4"]),
    # ---- z notatek
    tr_row("Nie mogę ogarnąć tej nowej reguły gramatycznej.", "get your head around",
           "I can't get my head around this new grammar rule.", "I can't get my head round this new grammar rule.",
           ("Idiom.", "<b>your</b> zmieniamy na zaimek dzierżawczy osoby: <i>my head, his head</i>."),
           "I can't get your head around this new grammar rule.", ["idiom"]),
    tr_row("Jest teraz spłukany, więc nie pojedzie z nami na wakacje.", "be hard up",
           "He's hard up at the moment, so he can't come on holiday with us.", "He's hard up right now, so he won't be coming on holiday with us.",
           ("Wyrażenie przymiotnikowe.", "<b>be + hard up</b> – odmieniamy <i>be</i>; to nie jest multi-word verb."),
           "", ["idiom"]),
    tr_row("Te stare buty się rozpadają – wyrzuć je!", "fall apart · throw away",
           "These old shoes are falling apart – throw them away!", "",
           ("Type 1 + Type 2.", "<b>fall apart</b> bez dopełnienia; <b>throw sth away</b> – zaimek w środku."),
           "…throw away them!", ["1", "2"]),
]


OUTPUTS = {
    "fce-grammar-multi-word-verbs-3a.tsv": GRAMMAR,
    "fce-phrasal-verbs-multi-word-verbs-3a.tsv": PV,
    "fce-use-of-english-multi-word-verbs-3a-translation.tsv": TR,
}

if __name__ == "__main__":
    for name, rows in OUTPUTS.items():
        write_tsv(name, rows)
